### ISSUE TITLE
Dockerfile/Docker Hub Documentation

### ISSUE THREAD

**Issue by LeeBergstrand** [neufeld/AXIOME2#13]
**Problem Description:**

The QIIME from Bioconda ships with UCLUST binaries. Robert Edgar gave them special permission to provide UCLUST for you as part of QIIME. Do we still need the user to bind mount in their own UCLUST/USEARCH binaries? I have had QIIME vis Bioconda work out fo the box before.

**Comment by jmtsuji** [comment]
@LeeBergstrand Yes, you are correct, and AXIOME2 has an option to use the QIIME-included version of USEARCH. However, users with high sample load can have AXIOME use their own provided binary of USEARCH (paid version; runs faster). This is what our lab does.

I should clean this up in the documentation. "Bring your own USEARCH" only applies if you want to run AXIOME with your own paid version.
